name: Changelog Generator

on:
  release:
    types: [created]

jobs:

  generate-changelog:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Generate Changelog
      id: generate-changelog
      uses: ./.github/actions/changelog-generator
    - name: Create Release
      uses: release-action/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ steps.generate-changelog.outputs.changelog }}
